services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    ports:
      - "30060:5432"
    networks:
      - odoo_network
    restart: always 

  odoo:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    depends_on:
      - db
    ports:
      - "30069:8069"
    volumes:
      - ./custom-addons:/mnt/extra-addons
      - ./config:/etc/odoo 
      - odoo-web-data:/var/lib/odoo/web/static
      - ./data:/var/lib/odoo
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - RABBITMQ_HOST=rabbitmq  
    networks:
      - odoo_network
    restart: always  

volumes:
  odoo-db-data:
  odoo-web-data:

networks:
  odoo_network:
    driver: bridge