services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - /data/postgres:/var/lib/postgresql/data
    ports:
      - "30060:5432"
    networks:
      - project_network  
    restart: always 

    
  rabbitmq:
    image: rabbitmq:management
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672" 
      - "15672:15672"
    networks:
      - project_network
    restart: always  # Added for automatic restart

  odoo:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    user: root
    depends_on:
      - db
      - rabbitmq
    ports:
      - "30069:8069"
    volumes:
      - ./custom-addons:/mnt/extra-addons
      - ./config:/etc/odoo
      - odoo-web-data:/var/lib/odoo/web/static
      - /data/odoo-data:/var/lib/odoo
    environment:
      - HOST=${ODOO_HOST}
      - USER=${ODOO_USER}
      - PASSWORD=${ODOO_PASSWORD}
      - RABBITMQ_HOST=rabbitmq
    networks:
      - project_network  
    restart: always  

volumes:
  odoo-db-data:
  odoo-web-data:
    driver: local

networks:
  project_network:
    driver: bridge


