name: Odoo CI/CD deploy Pipeline

on:
  push:
    branches:
      - Deployment  

jobs:
  build:
    name: Build & Test Odoo
    runs-on: self-hosted 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Load environment variables from .env
        run: |
          export $(grep -v '^#' .env | xargs)  # Laad .env bestand lokaal

      - name: Build Docker Image
        run: docker compose build

      - name: Test Docker Compose
        run: |
          docker compose --env-file ~/.env up -d
          sleep 10
          docker ps
          docker inspect --format='{{json .State.Health}}' $(docker ps -q) | jq
          docker compose down

  deploy:
    name: Deploy to Server
    needs: build
    runs-on: self-hosted  

    steps:
      - name: Pull latest code and restart containers
        run: |
          cd ~/kassa
          git pull origin Deployment
          docker compose down
          docker compose --env-file ../.env up -d
          docker system prune -af
