name: Odoo CI/CD deploy Pipeline

on:
  push:
    branches:
      - Deployment  

jobs:
  build:
    name: Build & Test Odoo
    runs-on: self-hosted 
    defaults:
      run:
        working-directory: /home/ehbstudent/kassa  

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Load environment variables from .env
        run: export $(grep -v '^#' /home/ehbstudent/.env | xargs)

      - name: Build Docker Image
        run: docker compose --env-file /home/ehbstudent/.env build

      - name: Test Docker Compose
        run: |
          docker compose --env-file /home/ehbstudent/.env up -d
          sleep 10
          docker ps
          docker inspect --format='{{json .State.Health}}' $(docker ps -q) | jq
          docker compose down

  deploy:
    name: Deploy to Server
    needs: build
    runs-on: self-hosted  
    environment: environment
    defaults:
      run:
        working-directory: /home/ehbstudent/kassa 

    steps:
      - name: Pull latest code and restart containers
        run: |
          git pull origin Deployment
          docker compose down
          docker compose --env-file /home/ehbstudent/.env up -d
